# 4.1.2: Promises 2

### `.catch`

Now we can talk more specifically about what .catch does and how to use it in the logic of our programs.

We'll use `pg` library promises as an example but any promise \(with or without libraries\) will have the same `.catch` behaviour.

On line 13 we exit out of this set of nested dependent queries because we know that without a valid recipe we can't go any further.

```javascript
let category = 'vegan';

client
  .query('SELECT * from categories WHERE name= $1', [category])
  .then((result) => {
    let categoryId = result.rows[0].id;
    return pool.query('SELECT * FROM recipes WHERE category_id = $1', [categoryId]);
  })
  .then((result) => {
    // check to see if we got results
    if (result.rows.length === 0) {
      throw 'no recipes';
    }

    let recipes = result.rows;

    // ...
  })
  .catch((error) => {
    // in Express.js we might respond 400 or 500.
    console.log(error);
  });
```

We can also see that if we throw in a normal promise it works the same way:

On line 21 we define the `catch` method that will deal with the `throw`.

```javascript
// random number representing between 0 and .999 seconds
const randomNumber = () => Math.floor(Math.random() * 1000);

// function that wraps setTimeout in a promise
const setDelay = (delay) => {
  console.log(`delaying ${delay}`);

  return new Promise((resolve, reject) => {
  
    // throw if we have to wait too long
    if (delay > 500) {
      throw "we'll wait too long";
    }

    setTimeout(() => {
      // timeout is over, resolve
      resolve(delay);
    }, delay);
  });
};

setDelay(randomNumber()).then((result) => {
  console.log('all done with delay');
}).catch((error) => {
  console.log('catching error');
  console.log(error);
});
```

Note that if we want to put the condition in the callback on line 14, we have to use `reject` instead of `throw`. `throw` / `catch` doesn't work for async callbacks _inside_ promise callbacks.

### `.all`

In promises sometimes we want to do a set of things that are not sequential, but only run the next thing after they are all done. `Promise.all` enables us to do that.

```javascript
const results = Promise.all([
    pool.query('SELECT * FROM recipes'),
    pool.query('SELECT * FROM users'),
    pool.query('SELECT * FROM categories')
]).then(allResults => {
    console.log(allResults);
});
```

#### Sequential Promises

The delay will be the sum of all the delays.

```javascript
const randomNumber = () => Math.floor(Math.random() * 1000);

const setDelay = (delay) => {
  console.log(`delaying ${delay}`);

  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(delay), delay);
  });
};

// do nested setTimeouts, one after the other
const result = setDelay(randomNumber()).then((resultOne) => {
  return setDelay(randomNumber()).then(resultTwo=>{
    return setDelay(randomNumber()).then(resultThree=>{
      return setDelay(randomNumber());
    });
  });
});

// run this when they are all done
result.then((number) => {
  console.log('all done');
  console.log(number);
});
```

#### Promise.all

The delay will be as long as the longest delay.

```javascript
const randomNumber = () => Math.floor(Math.random() * 1000);

const setDelay = (delay) => {
  console.log(`delaying: ${delay}`);

  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(delay), delay);
  });
};

// start all the setTimeouts
const result = Promise.all([
  setDelay(randomNumber()),
  setDelay(randomNumber()),
  setDelay(randomNumber()),
  setDelay(randomNumber()),
]);

result.then((number) => {
  console.log('all done');
  console.log(number);
});
```

## Exercise

Run the `setTimeout` code above.

