# 4.1.2: Promises 2

### `.catch`

Now we can talk more specifically about what .catch does and how to use it in the logic of our programs.

We'll use `pg` library promises as an example but any promise \(with or without libraries\) will have the same `.catch` behaviour.

On line 13 we exit out of this set of nested dependent queries because we know that without a valid recipe we can't go any further.

```text
let category = 'vegan';

client
  .query('SELECT * from categories WHERE name= $1', [category])
  .then(result => {
    let categoryId = result.rows[0].id;
    return pool.query('SELECT * FROM recipes WHERE category_id = $1', [categoryId]);
  })
  .then(result => {
  
    // check to see if we got results
    if( result.rows.length === 0 ){
      throw "no recipes";
    }
  
    let recipes = result.rows;
        
    // ...
  
  })
  .catch(error => {
  
    // in Express.js we might respond 400 or 500.
    console.log(error)
  })
```

We can also see that if we throw in a normal promise it works the same way:

On line 21 we define the `catch` method that will deal with the `throw`.

```text
const randomNumber = () => Math.floor(Math.random() * 1000);

const setDelay = (delay)=>{

  console.log(`delaying ${delay}`);

  return new Promise((resolve, reject)=>{

    if( delay > 500 ){
      throw "we'll wait too long";
    }

    setTimeout(()=> {
      resolve(delay);
    },delay);
  });
};

setDelay(randomNumber()).then((result) => {
  console.log("all done with delay");
}).catch((error) => {
  console.log("catching error");
  console.log(error);
});
```

Note that if we want to put the condition in the callback on line 14, we have to use `reject` instead of `throw`. `throw` / `catch` doesn't work for async callbacks _inside_ promise callbacks.

### `.all`

In promises sometimes we want to do a set of things that are not sequential, but only run the next thing after they are all done. Promise.all enables us to do that.

```
const results = Promise.all([
    pool.query('SELECT * FROM recipes'),
    pool.query('SELECT * FROM users'),
    pool.query('SELECT * FROM categories')
]);
```

#### Sequential Promises

The delay will be the sum of all the delays.

```text
const randomNumber = () => Math.floor(Math.random() * 1000);

const setDelay = (delay)=>{

  console.log(`delaying ${delay}`);

  return new Promise((resolve, reject)=>{
    setTimeout(()=> resolve(delay) ,delay);
  });
};

const result = setDelay(randomNumber()).then((result) => {
  return setDelay(randomNumber()).then((result)=>{
    return setDelay(randomNumber()).then((result)=>{
      return setDelay(randomNumber())
    });
  })
});

result.then((result)=>{
  console.log("all done");
  console.log(result);
});
```

#### Promise.all

The delay will be as long as the longest delay.

```text
const randomNumber = () => Math.floor(Math.random() * 1000);

const setDelay = (delay)=>{

  console.log(`delaying ${delay}`);

  return new Promise((resolve, reject)=>{
    setTimeout(()=> resolve(delay) ,delay);
  });
};

const result = Promise.all([
  setDelay(randomNumber()),
  setDelay(randomNumber()),
  setDelay(randomNumber()),
  setDelay(randomNumber()),
]);

result.then((result)=>{
  console.log("all done");
  console.log(result);
});
```

## Exercise

Run the `setTimeout` code above.

