# 4.1.3: Async Await

## Introduction

Async and await, commonly abbreviated as async/await, is an ES6 syntax built upon Promises that enables writing asynchronous JavaScript in a synchronous manner without callbacks. The `async` keyword specifies that a given function is asynchronous and returns a Promise, and the `await` keyword will wait on a given Promise to resolve before proceeding to the next line. `async` and `await` keywords must be used together; it is not meaningful to use `async` without `await`, and it is invalid syntax to use `await` without `async`.

## Synchronous Function Call

Synchronous order with a function call.

```javascript
const randomNumber = () => Math.floor(Math.random() * 1000);

const setDelay = (delay) => {
  console.log(`delaying ${delay}`);

  setTimeout(() => {
    console.log('done with timeout');
  }, delay);
};

const doStuff = () => {
  console.log('setting timeout');
  setDelay(randomNumber());
  console.log('after call settimeout');
};

console.log('about to call do stuff');
doStuff();
console.log('finished call do stuff');
```

Outputs

```text
about to call do stuff
setting timeout
delaying 852
after call settimeout
finished call do stuff
done with timeout
```

## Asynchronous Function Call with Promise and Async/Await

Define an async function.

```javascript
const randomNumber = () => Math.floor(Math.random() * 1000);

const setDelay = (delay) => {
  console.log(`delaying ${delay}`);

  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(delay);
    }, delay);
  });
};

const doStuff = async () => {
  console.log('about to set timeout');
  await setDelay(randomNumber());
  console.log('after call settimeout');
};

console.log('about to call do stuff');
doStuff();
console.log('done with timeout');
console.log('finished call do stuff');
```

Outputs:

```text
about to call do stuff
about to set timeout
delaying 934
done with timeout
finished call do stuff
after call settimeout
```

The magic of async await is on line 17 and 18. Notice that the `setTimeout` causes a delay between these lines. This code looks like "normal" JavaScript, but in fact, it is running unlike our other JavaScript we've written so far. It is pausing on a line and waiting for something to happen.

## pg / Express.js with Async / Await

```javascript
app.get('/:id', async (request, response) => {
  const { id } = request.params;
  console.log('making query');
  const { rows } = await db.query('SELECT * FROM users WHERE id = $1', [id]);
  console.log('done with query');
  res.send(rows[0]);
});
```

`pg` example from [here](https://node-postgres.com/guides/async-express).

## Async Await and Try / Catch

From this promise `.catch` example, how do we keep the error handling of `.catch`, and still convert this code from promises to async / await? We can go back to the original syntax of the `try` block.

#### Promises

```javascript
let category = 'vegan';

client
  .query('SELECT * from categories WHERE name= $1', [category])
  .then((result) => {
    let categoryId = result.rows[0].id;
    return client.query('SELECT * FROM recipes WHERE category_id = $1', [
      categoryId,
    ]);
  })
  .then((result) => {
    let recipes = result.rows;

    // ...
  })
  .catch((error) => {
    // in Express.js we might respond 400 or 500.
    console.log(error);
  });
```

#### Async / Await

```javascript
const getData = async (category) => {
  try {
    const categories = await client.query(
      'SELECT * from categories WHERE name= $1',
      [category]
    );

    let categoryId = categories[0].id;
    const recipes = await client.query(
      'SELECT * FROM recipes WHERE category_id = $1',
      [categoryId]
    );

    // ...

    // catch errors thrown by client.query
  } catch (error) {
    console.log(error);
  }
};

getData('vegan');
```

## Pause

Note that we can write async / await with the syntax that appears to cause our program to pause on a given line. However, note that other things can continue to run while it waits at that line.

```javascript
const setDelay = (delay) => {
  console.log(`delaying ${delay}`);

  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(delay);
    }, delay);
  });
};

const doStuff = async (delay) => {
  console.log(`about to set timeout with delay: ${delay}`);
  await setDelay(delay);
  console.log(`after call settimeout with delay: ${delay}`);
};

console.log('about to call do stuff, wait a second');
doStuff(1000);
console.log('about to call do stuff 2nd time, wait .7 sec');
doStuff(700);
console.log('done with timeout');
console.log('finished call do stuff');
```

Outputs:

```text
about to call do stuff, wait a second
about to set timeout with delay: 1000
delaying 1000
about to call do stuff 2nd time, wait .7 sec
about to set timeout with delay: 700
delaying 700
done with timeout
finished call do stuff
after call settimeout with delay: 700
after call settimeout with delay: 1000
```

If everything was truly frozen between line 14 and 16, our function call on line 22 would happen afterwards.
